config/routes.rb
Rails.application.routes.draw do
  
  resources :collections

  root to: "welcome#index"
  get 'help' => "welcome#help"
  get 'about' => "welcome#about"

  resources :recipes do
    member do
      post :add_recipe
      post :remove_recipe
    end

    collection do
      post :search
    end
  end

  get 'register' => 'users#new'
  resources :users do
    member do
      post :add_friend
      post :remove_friend
    end
  end
  post 'facebook/share' => 'users#facebook_share'

  get 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#new'
  get '/auth/facebook' => 'auth#facebook'
  get 'auth/facebook/callback' => 'sessions#create'
  get 'auth/facebook/rerequest' => 'auth#rerequest_facebook'

  resources :sessions, only: [:new, :create, :destroy]
  
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_and_belongs_to_many :recipes
  belongs_to :user

  after_find do |collection|
    collection.count_of_recipes = collection.recipes.count
    collection.save!
  end

  def add_recipe(recipe)
    unless self.recipes.exists? recipe
      if self.user.recipes.exists? recipe
        new_recipe = recipe
      else
        new_recipe = self.user.recipes.build
        new_recipe.name = recipe.name
        new_recipe.ingredients = recipe.ingredients
        new_recipe.directions = recipe.directions
        new_recipe.image = recipe.image
        new_recipe.save!
        new_recipe.reload
      end
      self.recipes << new_recipe
      return true
    end
    return false
  end

  def remove_recipe(recipe)
    if self.recipes.exists? recipe then self.recipes.delete recipe end
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy, :add_recipe, :remove_recipe]

  before_filter only: [:edit, :update, :destroy] do |c|
    c.send(:allowed?, @collection)
  end

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.where("count_of_recipes > 0")
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name, :user_id)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.haml
= form_for @collection do |f|
  - if @collection.errors.any?
    .alert-danger
      %h2= "#{pluralize(@collection.errors.count, "error")} prohibited this recipe from being saved:"
      %ul
        - @collection.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.hidden_field :user_id, value: current_user.id
    = f.label :name
    = f.text_field :name, placeholder: "Appetizers", class: "form-control"
    %br
  .form-group
    = f.submit 'Save', class: "btn btn-lg btn-info btn-block"

app/views/collections/edit.html.haml
.container
  .col-md-8.col-md-offset-2
    %h1 Editing collection

    = render 'form'

    = link_to 'Show', @collection
    \|
    = link_to 'Back', collections_path

app/views/collections/index.html.haml
.container
  - @collections.each do |collection|
    .col-md-3{style: "height:175px;"}
      .thumbnail{style: "height:100%;"}
        / = link_to image_tag(collection.recipes.first.list_image), collection, style: "max-height:80%;"
        / %br
        / = link_to "#{truncate(collection.name.titleize + ' from ' + collection.user.first_name.titleize, length: 25)}", collection.user
        %a{href:collection_path(collection)}
          = image_tag collection.recipes.first.list_image, class: "img-thumbnail", style: "margin-top:10px;max-height:80%;"
        %div{style:"position:absolute;bottom:0"}= truncate(collection.name.titleize + " from " + collection.user.first_name.titleize, length: 18)
        .pull-right{style:"position:absolute;top:0;"}= pin_it_button :media => image_url(collection.recipes.first.image.url), :description => "#{collection.name.titleize}, a collection of delicious recipes from #{collection.user.first_name.titleize} over at http://recipes.readydevgo.com", :url => collection_url(collection),:count_layout => 'horizontal'

app/views/collections/new.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      %h1 New collection

      = render 'form'

      = link_to 'Back', collections_path

app/views/collections/show.html.haml
.container
  .row
    %h1{style:"display:inline;"}= @collection.name.titleize
    - if current_user == @collection.user
      .pull-right
        = link_to 'Edit', edit_collection_path(@collection)
        \|
        = link_to 'Back', collections_path
  - @collection.recipes.each do |recipe|
    .col-sm-6.col-md-4
      .thumbnail
        = link_to image_tag(recipe.image.url, style: "height: 250px;"), recipe
        .pull-left{style:"position:absolute;top:0;"}= pin_it_button :media => image_url(recipe.image.url), :description => recipe.name, :url => recipe_url(recipe),:count_layout => 'horizontal'
        = link_to "by #{recipe.user.first_name}", recipe.user, class: "pull-right", style: "margin-top:-20px;position:relative;background-color:rgba(255,255,255,0.5);color:#333;"
      = link_to "Remove", remove_recipe_recipe_path(recipe, collection_id: @collection.id), class: 'btn btn-sm btn-warning', style: "margin-top:-20px;color:#fff;", method: :post