config/routes.rb
Rails.application.routes.draw do
  
  resources :collections

  root to: "welcome#index"
  get 'help' => "welcome#help"
  get 'about' => "welcome#about"

  resources :recipes do
    member do
      post :add_recipe
      post :remove_recipe
    end

    collection do
      post :search
    end
  end

  get 'register' => 'users#new'
  resources :users do
    member do
      post :add_friend
      post :remove_friend
    end
  end
  post 'facebook/share' => 'users#facebook_share'

  get 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#new'
  get '/auth/facebook' => 'auth#facebook'
  get 'auth/facebook/callback' => 'sessions#create'
  get 'auth/facebook/rerequest' => 'auth#rerequest_facebook'

  resources :sessions, only: [:new, :create, :destroy]
  
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  validates_presence_of :name, :ingredients, :directions

  belongs_to :user
  has_and_belongs_to_many :collections

  mount_uploader :image, ImageUploader

  def list_image
    self.image.versions[:web].preview.url
  end

  def ingredients_list
    ings = self.ingredients.scan(/.*$/)
    ings.keep_if {|x|x.present?}
    ings.map do |i|
      if i.include? "\r"
        i.gsub!("\r", "")
      end
    end
    ings
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :add_recipe, :remove_recipe]

  before_filter only: [:edit, :update, :destroy] do |c|
    c.send(:allowed?, @recipe)
  end

  # GET /recipes
  # GET /recipes.json
  def index
    search_q = params[:q]
    @q = Recipe.search(search_q)
    @recipes = Recipe.all
  end

  def search
    search_q = params[:q]
    @q = Recipe.search(search_q)
    @recipes = @q.result(distinct: true)
    render :index
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_recipe
    collection = Collection.find(params[:collection_id])
    
    respond_to do |format|
      if collection.add_recipe(@recipe)
        format.html { redirect_to :back, notice: 'Recipe was added to collection.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :back, notice: 'Oops, we couldn\'t add that one. :(' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_recipe
    collection = Collection.find(params[:collection_id])
    collection.remove_recipe(@recipe)
    respond_to do |format|
      if !collection.recipes.exists? @recipe
        format.html { redirect_to :back, notice: 'Recipe was removed from collection.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :back, notice: 'Oops, we couldn\'t find or remove that one. :(' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :directions, :user_id, :image, :ingredients)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.haml
= form_for @recipe do |f|
  - if @recipe.errors.any?
    .alert-danger
      %h2= "#{pluralize(@recipe.errors.count, "error")} prohibited this recipe from being saved:"
      %ul
        - @recipe.errors.full_messages.each do |msg|
          %li= msg
  = f.hidden_field :user_id, value: current_user.id
  .form-group
    = f.label :name
    = f.text_field :name, placeholder: "Spaghetti", class: "form-control"
  .form-group
    = f.label :ingredients
    = f.text_area :ingredients, placeholder: "1/2 cup dry spaghetti\n1 cup tomato sauce", class: "form-control", style: "min-height:100px;"
  .form-group
    = f.label :directions
    = f.text_area :directions, placeholder: "Bring 2qts of water to boil...", class: "form-control", style: "min-height:150px;"
  .form-group
    = f.label :image
    = f.file_field :image, class: "form-control"
    = f.hidden_field :image_cache
  .form-group
    = f.submit 'Save', class: "btn btn-lg btn-info btn-block"

app/views/recipes/_recipe.html.haml
.well.centered{style:"height:160px;position:relative;", itemscope: true, itemtype: 'http://schema.org/Recipe'}
  %meta{itemprop: 'url', content: recipe_path(recipe)}
  - recipe.ingredients_list.each do |i|
    %meta{itemprop: 'ingredients', content: i}
  %meta{itemprop: 'recipeInstructions', content: recipe.directions}
  %a{href:recipe_path(recipe)}
    = image_tag recipe.list_image, class: "img-thumbnail", style: "margin-top:10px;max-height:80%;", itemprop: 'image'
  %div{style:"position:absolute;bottom:0", itemprop: 'name'}= truncate(recipe.name, length: 18)
  .pull-right{style:"position:absolute;top:0;"}= pin_it_button :media => image_url(recipe.image.url), :description => recipe.name, :url => recipe_url(recipe),:count_layout => 'horizontal'
  %br

app/views/recipes/_recipe_index.html.haml
.col-sm-6.col-md-4
  .thumbnail
    = link_to image_tag(recipe.image.url, style: "height: 250px;"), recipe
    .pull-left{style:"position:absolute;top:0;"}= pin_it_button :media => image_url(recipe.image.url), :description => recipe.name, :url => recipe_url(recipe),:count_layout => 'horizontal'
    = link_to "by #{recipe.user.first_name}", recipe.user, class: "pull-right", style: "margin-top:-20px;position:relative;background-color:rgba(255,255,255,0.5);color:#333;"

app/views/recipes/edit.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      %h1 Editing recipe

      = render 'form'

      = link_to 'Show', @recipe, style:"color:#fff;"
      \|
      = link_to 'Back', recipes_path, style:"color:#fff;"

app/views/recipes/index.html.haml
%meta{content: 'dapperchef.com', property: 'og:site'}
.container
  - @recipes.order(created_at: :desc).each do |recipe|
    .col-sm-6.col-md-4
      .thumbnail{itemscope: true, itemtype: 'http://schema.org/Recipe'}
        %meta{itemprop: 'name', content: recipe.name}
        %meta{itemprop: 'image', content: recipe.image.url}
        - recipe.ingredients_list.each do |i|
          %meta{itemprop: 'ingredients', content: i}
        %meta{itemprop: 'recipeInstructions', content: recipe.directions}
        %meta{itemprop: 'url', content: recipe_path(recipe)}
        = link_to image_tag(recipe.image.url, style: "height: 250px;"), recipe
        .pull-left{style:"position:absolute;top:0;"}= pin_it_button :media => image_url(recipe.image.url), :description => recipe.name, :url => recipe_url(recipe),:count_layout => 'horizontal'
        = link_to "by #{recipe.user.first_name}", recipe.user, class: "pull-right", style: "margin-top:-20px;position:relative;background-color:rgba(255,255,255,0.5);color:#333;"

app/views/recipes/new.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      %h1 New recipe

      = render 'form'

      = link_to 'Back', root_path, style:"color:#fff;", class: "pull-right"

app/views/recipes/show.html.haml
.container{itemscope: true, itemtype: 'http://schema.org/Recipe'}
  .row
    .col-md-8.col-md-offset-2
      .panel.panel-info
        .panel-heading
          .row
            %h3{style:"display:inline;padding-left:5px;", itemprop: 'name'}
              = @recipe.name
            %meta{itemprop: 'url', content: recipe_url(@recipe)}
            - if current_user == @recipe.user
              .pull-right{style:"margin-right:5px;"}
                = link_to 'Edit', edit_recipe_path(@recipe), style: "color:#fff;"
                \|
                = link_to 'Back', recipes_path, style: "color:#fff;"
                \|
                = link_to 'Delete', @recipe, method: :delete, style: "color:#fff;"
        .panel-body
          .thumbnail
            = image_tag @recipe.image.url, itemprop: 'image'
          .well
            %p= simple_format(@recipe.ingredients)
            - @recipe.ingredients_list.each do |i|
              %p{itemprop: 'ingredients', hidden: true}
                i
          = simple_format(@recipe.directions)
      .pull-left
        = link_to 'Share on Facebook', facebook_share_path(recipe_id: @recipe.id), class: "btn btn-lg btn-primary", method: :post
      .pull-right
        = form_tag add_recipe_recipe_path(@recipe), class: "form-inline" do
          .form-group
            = select_tag :collection_id, options_from_collection_for_select(current_user.collections.collect, "id", "name"), class: "form-control", style: "display:inline;"
            = submit_tag "Add to Collection", class: "btn btn-lg btn-primary"
%br
%br

/ %meta{property:"og:url", content:recipe_path(@recipe)}
/ %meta{property:"og:title", content:@recipe.name.titleize}
/ %meta{property:"og:description", content:"This recipe is awesome!"}
/ %meta{property:"og:image", content:@recipe.image.url}