config/routes.rb
Rails.application.routes.draw do
  
  resources :collections

  root to: "welcome#index"
  get 'help' => "welcome#help"
  get 'about' => "welcome#about"

  resources :recipes do
    member do
      post :add_recipe
      post :remove_recipe
    end

    collection do
      post :search
    end
  end

  get 'register' => 'users#new'
  resources :users do
    member do
      post :add_friend
      post :remove_friend
    end
  end
  post 'facebook/share' => 'users#facebook_share'

  get 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#new'
  get '/auth/facebook' => 'auth#facebook'
  get 'auth/facebook/callback' => 'sessions#create'
  get 'auth/facebook/rerequest' => 'auth#rerequest_facebook'

  resources :sessions, only: [:new, :create, :destroy]
  
end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :recipes, dependent: :destroy
  has_many :collections, dependent: :destroy
  has_and_belongs_to_many :friends,
      class_name: "User",
      foreign_key: "this_user_id",
      association_foreign_key: "other_user_id"

  mount_uploader :image, ImageUploader

  after_create 'self.welcome_user'
  before_destroy 'self.clear_friends'

  def self.from_omniauth(auth)
    create! do |user|  
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.remote_image_url = auth.info.image.gsub('http://','https://')
      user.facebook_token = auth.credentials.token
    end
  end

  def welcome_user
    UserMailer.welcome_email(self).deliver
  end

  def profile_image
    self.image.versions[:web].preview.url
  end

  def list_image
    self.image.versions[:web].thumb.url
  end

  def post(recipe, url)
    content = "This recipe for #{recipe.name} looks amazing. Check it out at #{url}"
    graph.put_wall_post(content)
  end

  def add_friend(user)
    self.friends << user unless self.friends.exists? user
    user.friends << self unless user.friends.exists? self
  end

  def clear_friends
    self.friends.each do |friend|
      delete_friend(friend)
    end
  end

  def delete_friend(friend)
    self.friends.delete friend
    friend.friends.delete self
  end

  private

  def graph
    @graph = Koala::Facebook::API.new(self.facebook_token)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_filter :ensure_logged_in, only: [:new, :create]
  before_action :set_user, only: [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    unless current_user.admin == true
      redirect_to :back, notice: "Only admins can do that :)."
    end
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    user_id = params[:id]
    @user = User.find(user_id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save

        UserMailer.welcome_email(@user).deliver
        format.html { redirect_to login_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def facebook_share
    recipe_id = params[:recipe_id]
    recipe = Recipe.find(recipe_id)
    if check_permissions
      current_user.post(recipe, recipe_url(recipe))
      redirect_to :back, notice: "You've shared this recipe!"
    else
      redirect_to :back, notice: "Oops, we don't have permission to post this for you. :("
    end
  end

  def add_friend
    new_friend = User.find(params[:friend_id])
    current_user.add_friend(new_friend)
    redirect_to :back, notice: "User was successfully added to friends."
  end

  def remove_friend
    friend = User.find(params[:friend_id])
    current_user.delete_friend(friend)
    redirect_to :back, notice: "User was successfully removed from friends."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(current_user.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :image)
    end

    def content(recipe)
      "#{recipe_path(recipe)}"
    end

    def check_permissions
      permissions = graph.get_object("me/permissions")
      status = permissions.select { |perm_hash| perm_hash["permission"] == "publish_actions" }.first
      if status == nil || status["status"] != "granted"
        return false
      else
        return true
      end
    end

    def graph
      @graph = Koala::Facebook::API.new(current_user.facebook_token)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    .alert-danger
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :first_name
    = f.text_field :first_name, class: "form-control"
  .form-group
    = f.label :last_name
    = f.text_field :last_name, class: "form-control"
  .form-group
    = f.label :email
    = f.text_field :email, class: "form-control"
  .form-group
    = f.label :image
    = f.file_field :image, class: "form-control"
    = f.hidden_field :image_cache
    .centered
      %br
      = image_tag(@user.image.web.preview.url) if @user.image?
  .form-group
    = f.submit 'Submit', class: "btn btn-lg btn-success btn-block"

app/views/users/edit.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      %h1 Editing user

      = render 'form'

      .pull-right
        = link_to 'Show', @user, style:"color:#fff;"
        \|
        = link_to 'Back', users_path, style:"color:#fff;"

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th First name
    %th Last name
    %th Email
    %th Password digest
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.first_name
      %td= user.last_name
      %td= user.email
      %td= user.password_digest
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      %h1 Sign Up

      = render 'form'

      = link_to 'Back', login_path, class: "pull-right", style: "color:#fff;"

app/views/users/show.html.haml
.container
  .row
    .col-md-4
      #profile
        .well#profile-image.centered
          = image_tag @user.profile_image
          %br
          = @user.first_name
        .well.centered#friends-list
          - unless @user == current_user
            - if @user.friends.include? current_user
              = button_to "Unfriend", remove_friend_user_path(current_user.id, friend_id: @user.id), class: "btn btn-xs btn-warning"
            - else
              = button_to "Add Friend", add_friend_user_path(current_user.id, friend_id: @user.id), class: "btn btn-xs btn-success"
          %legend= "#{@user.first_name.titleize}'s Friends"
          - @user.friends.order(:first_name).each do |friend|
            = link_to image_tag(friend.list_image), friend
    .col-md-8
      #recipes
        %legend= "#{@user.first_name.titleize}'s Recipes"
        .row
          - @user.recipes.order(:name).each do |recipe|
            .col-sm-6.col-md-4
              .thumbnail
                = link_to image_tag(recipe.image.url, style: "height: 175px;"), recipe
                .pull-left{style:"position:absolute;top:0;"}= pin_it_button :media => image_url(recipe.image.url), :description => recipe.name, :url => recipe_url(recipe),:count_layout => 'horizontal'
                = link_to "by #{recipe.user.first_name}", recipe.user, class: "pull-right", style: "margin-top:-20px;position:relative;background-color:rgba(255,255,255,0.5);color:#333;"