config/routes.rb
Rails.application.routes.draw do
  
  resources :collections

  root to: "welcome#index"
  get 'help' => "welcome#help"
  get 'about' => "welcome#about"

  resources :recipes do
    member do
      post :add_recipe
      post :remove_recipe
    end

    collection do
      post :search
    end
  end

  get 'register' => 'users#new'
  resources :users do
    member do
      post :add_friend
      post :remove_friend
    end
  end
  post 'facebook/share' => 'users#facebook_share'

  get 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#new'
  get '/auth/facebook' => 'auth#facebook'
  get 'auth/facebook/callback' => 'sessions#create'
  get 'auth/facebook/rerequest' => 'auth#rerequest_facebook'

  resources :sessions, only: [:new, :create, :destroy]
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_filter :ensure_logged_in, only: [:about, :help]
  
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.haml
.container
  %h1
    %strong{style:"font-size:2em"} Dapper Chef
  %h3 After signing in using Facebook, users can upload recipes (along with photos), organize them into collections, collect other users' recipes, and share what they enjoy by pinning it on Pinterest.

.container{style:"margin-top:50px;padding:25px;background-color:#fff;"}
  .row{style:"padding:50px 0;"}
    .col-md-4.col-md-offset-2
      %i.fa.fa-facebook.fa-5x
    .col-md-6
      %h1 Sign in with Facebook
  %hr
  .row{style:"padding:50px 0;"}
    .col-md-6.col-md-offset-2
      %h1 Explore New Recipes
    .col-md-4
      %i.fa.fa-spoon.fa-5x
  %hr
  .row{style:"padding:50px 0;"}
    .col-md-4.col-md-offset-2
      %i.fa.fa-pinterest.fa-5x
    .col-md-6
      %h1 Socialize and Share
.container{style:"padding:50px 0;"}
  .col-md-6.col-md-offset-3.centered
    %h1{style:"padding-bottom:50px;"} What are you waiting for?
    = link_to "Join Today!", login_path, class: "btn btn-lg btn-block btn-primary", style: "color:#fff;"

app/views/welcome/help.html.haml
.container
  .row
    .col-md-8.col-md-offset-2{style:"font-size:1.5em;"}
      %legend Help or Concerns?
      Thanks so much for trying Dapper Chef. This is a personal project for my wonderful wife, Angela, and her cooking compadres.
      %br
      %br
      This means all issues or concerns are handled by your's truly (that's me), so please contact me if you need anything or have questions. You can reach me by email at
      = link_to "david@readydevgo.com ", "mailto:david@readydevgo.com"
      or on Twitter at 
      = link_to "@developgrr", "http://twitter.com/developgrr", target: "_blank"
      \.
      %br
      %br
      Again, thanks for trying out the app!
      %br
      %h3 - David

app/views/welcome/index.html.haml
.container{style:"padding-bottom:100px;"}
  .row
    .col-md-2
      #profile
        .well#profile-image.centered
          = link_to image_tag(current_user.profile_image, class: "img-responsive"), current_user
          %br
          = current_user.first_name
        = link_to "New Recipe", new_recipe_path, style: "color:#fff;", class: "btn btn-lg btn-success btn-block"
        = link_to "New Collection", new_collection_path, style: "color:#fff;", class: "btn btn-lg btn-info btn-block"
        %hr
        .centered
          %h3 Your Awesome Collections
          %hr
          - current_user.collections.order(:name).each do |coll|
            = link_to "#{coll.name.titleize}", coll, class: "btn btn-primary btn-block", style:"color:#fff;"
    .col-md-6
      #recipes
        %meta{content: 'dapperchef.com', property: 'og:site'}
        %legend Your Classy Kitchen
        .row
          - current_user.recipes.order(:name).each do |recipe|
            .col-md-6.col-lg-4
              = render recipe
    .col-md-4
      #friends
        .well.centered#friends-list
          %legend= "#{current_user.first_name.titleize}'s Friends"
          - current_user.friends.order(:first_name).each do |friend|
            = link_to image_tag(friend.list_image), friend